using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Client.UserInterface.Systems.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class SeparatedChatGameScreen : InGameScreen
{
    public SeparatedChatGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.TopLeft, margin: 5);
        SetAnchorAndMarginPreset(TopLeftContainer, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.TopLeft, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.Center, margin: 10);
        SetAnchorAndMarginPreset(Targeting, LayoutPreset.TopLeft, margin: 5);

        Inventory.Margin = new Thickness(5f, 5f);

        ScreenContainer.OnSplitResizeFinished += () =>
            OnChatResized?.Invoke(new Vector2(ScreenContainer.SplitFraction, 0));

        OnThemeUpdated();
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {
        ScreenContainer.DesiredSplitCenter = size.X;
        ScreenContainer.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
    }

    protected override void OnThemeUpdated()
    {
        MainInfoBackground.Texture = Theme.ResolveTexture("main_info_background");
        RightPanelTopBackground.Texture = Theme.ResolveTexture("right_panel_top_slot");
        LeftPanel.Texture = Theme.ResolveTexture("left_panel_background");
        RightPanel.Texture = Theme.ResolveTexture("right_panel_background");
    }
}
