
using System.Numerics;
using Content.Client.UserInterface.Systems.NativeActions.Controls;
using Content.Shared._White.Intent;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.NativeActions.Widgets;

[GenerateTypedNameReferences]
public sealed partial class NativeActionsGui : UIWidget
{

    private readonly NativeActionsUIController _controller;

    public NativeActionsGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _controller = UserInterfaceManager.GetUIController<NativeActionsUIController>();
    }
}
