
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.Voting.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.State;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        //private readonly ShaderInstance _shader;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            // FIXME: For some reasong, it cannot be work with animated background.
            // if we wanna use animated backs with shaders - make multiple textures and switch it
            //_shader = _prototypeManager.Index<ShaderPrototype>("LobbyCRT").InstanceUnique();
            //Background.ShaderOverride = _shader;

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            CallVoteButton.OnPressed += _ => new VoteCallMenu().OpenCentered();
        }

        public void ToggleCharacterSetup()
        {
            UserInterfaceManager.GetUIController<LobbyUIController>().ToggleCharacterSetup();
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            //CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    //CharacterSetupState.Visible = true;

                    /* BUGGED
                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                        RightSide.Visible = false;
                    */

                    //RightSide.Visible = false;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        public enum LobbyGuiState : byte
        {
            /// The default state, i.e., what's seen on launch.
            Default,
            /// The character setup state.
            CharacterSetup,
        }
    }
}
